using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Torch : MonoBehaviour
{
    [SerializeField] bool isLit;
    [SerializeField] float torchLitDelay = 1f;

    [SerializeField] AudioClip torchSound;
    [SerializeField] AudioClip lightTorchSound;
    [SerializeField] AudioClip putOutTorchSound;
    [SerializeField] AudioClip hitSound;

    [SerializeField] AudioSource audioSource;

    private PlayerMovement playerMovement;

    void Start()
    {
        playerMovement = GetComponent<PlayerMovement>();

        audioSource.clip = torchSound;
        audioSource.playOnAwake = true;
        audioSource.loop = true;

        if(isLit) {
            audioSource.Play();
        }
    }

    void Update()
    {
        // H채mtar in golvet spelaren st책r p책.
        
        string groundTag = playerMovement.GetGroundTag();

        if (groundTag == "Carpet")
        {
            if (!isLit)
            {
                
                ToggleIsLit(true);
                Debug.Log("Fackla aktiverad");
            }
        }
        else if (groundTag == "Tile")
        {
            if (isLit)
            {
                ToggleIsLit(false);
                Debug.Log("Fackla deaktiverad");
            }
        }
        
    }

    public bool GetIsLit(){
        return isLit;
    }

    public void ToggleIsLit(bool state) {
        isLit = state;
        if(!isLit){
            audioSource.Stop();
            audioSource.PlayOneShot(putOutTorchSound);
        }
        
        if(isLit) {
            audioSource.PlayOneShot(lightTorchSound);
            audioSource.PlayDelayed(torchLitDelay);
            Debug.Log("t채nd fackla");
        }
        
    }

    public void PlayHitSound() {
        if(hitSound != null  && audioSource != null) {
            audioSource.PlayOneShot(hitSound);
        }
    }

}
